name: GitHub Actions Demo
run-name: ${{ github.actor}} is learning GitHub Actions
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/*'
  pull_request: 
    branches: [main]
  schedule: 
    - cron: '15 6 * * 0'
  workflow_dispatch:
    jobs:
      Build:
        runs-on: ubuntu-latest
        steps:

          - name: Output details
            run: |
              echo "This job was triggereed by event: ${{github.event_name}}"
              echo "This branch that triggered this: ${{github.ref}}"
              echo "This is the repository name: ${{github.repository}}"

          - uses: actions/checkout@v4

          - name: List all files in repo
            run: |
              echo "The repo (${{github.repository}}) contains these files:"
              tree
