name: CI build for Docker Action
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        required: true
        description: 'A test variable name'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: mk833

      - name: Output the time set in the container
        run: echo "The time that the container output was ${{steps.hello-action.outputs.time}} when the action said hello"
